//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_mono.wserv {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="ws_mono.wserv", ConfigurationName="testeSoap")]
public interface testeSoap {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.example.org/AddNumbers")]
    int AddNumbers(int number1, int number2);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.example.org/AddNumbers", AsyncPattern=true)]
    System.IAsyncResult BeginAddNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState);
    
    int EndAddNumbers(System.IAsyncResult result);
}

public interface testeSoapChannel : testeSoap, System.ServiceModel.IClientChannel {
}

public class testeSoapClient : System.ServiceModel.ClientBase<testeSoap>, testeSoap {
    
    public testeSoapClient() {
    }
    
    public testeSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public testeSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public testeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public testeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public int AddNumbers(int number1, int number2) {
        return base.Channel.AddNumbers(number1, number2);
    }
    
    public System.IAsyncResult BeginAddNumbers(int number1, int number2, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginAddNumbers(number1, number2, asyncCallback, userState);
    }
    
    public int EndAddNumbers(System.IAsyncResult result) {
        return base.Channel.EndAddNumbers(result);
    }
}
namespace www.example.org {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddNumbers", Namespace="http://www.example.org/")]
    public partial class AddNumbers : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int number1Field;
        
        private int number2Field;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int number1 {
            get {
                return this.number1Field;
            }
            set {
                this.number1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int number2 {
            get {
                return this.number2Field;
            }
            set {
                this.number2Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddNumbersResponse", Namespace="http://www.example.org/")]
    public partial class AddNumbersResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AddNumbersResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AddNumbersResult {
            get {
                return this.AddNumbersResultField;
            }
            set {
                this.AddNumbersResultField = value;
            }
        }
    }
}
